baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "graysx"

## Site Settings
[params]
logo = "assets/img/logo.webp"
favicon = "assets/favicon.png"
address = "test adresse"